### ISSUE TITLE
Footer background color

### ISSUE THREAD

**Issue by nicholasdly** [nicholasdly/tomatera#23]
Footer background color is currently the same color as the body; should be changed to #1E1E1E.

**Comment by Halim-Shams** [comment]
I wanna work on this project.

**Comment by nicholasdly** [comment]
> I wanna work on this project.

Hi Halim! Tomatera is primarily an independent project at the moment, but I will occassionally have small issues listed that can be solved by anyone! If you see an issue you would like to tackle, feel free to fork the repository, take your shot at fixing the issue, and make a pull request.
